### ISSUE TITLE
Question : is RadioML dataset correct?

### ISSUE THREAD

**Issue by pfeatherstone** [brysef/rfml#1]
@brysef Did you find irregularities with the RadioML dataset? Can you look at [this](https://github.com/radioML/dataset/issues/25) please?

**Comment by brysef** [comment]
@pfeatherstone Yes, I've found multiple irregularities with the RadioML dataset.  Off the top of my head (I haven't used this in over a year so double check me): SNRs aren't correct, the fading is too slow IMO, multi-path profile is static which is unrealistic, and a few issues with the analog modulation schemes.  Despite all these issues it is still the best *open source* dataset for modulation classification that I'm aware of because it takes a lot of effort to open source a dataset like this -- most others I've seen put out have had much fewer classes.  If that has changed, especially with regards to the OTA dataset, then I'd appreciate it if you recommended me a new one!

That said, this repository doesn't provide the RadioML dataset, it only provides a Python wrapper for downloading and using it, and I'm not affiliated with those that do provide the data.  Moreover, I've only included the 2016 version of the dataset which has an open sourced flow graph to generate the synthetic data (that you can somewhat easily fix the issues in that I mentioned above if you're familiar with GNU Radio).  Therefore, I'm pretty confident that the issue you linked, that the modulation labels are incorrect, does not apply to the RadioML.2016.x datasets that this repository provides wrappers for.  But please correct me if I'm wrong!

**Comment by pfeatherstone** [comment]
I'm fairly certain my issues were with the 2018.01A dataset. Again, last i checked was last year. I'm downloading it again and gonna check.
